# Generated by Django 2.0.6 on 2018-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20180617_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='skill',
            field=models.CharField(default='', help_text="e.g. 'Leadership'", max_length=255),
            preserve_default=False,
        ),
    ]
