# Generated by Django 2.0.6 on 2018-06-17 14:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_container_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='resources',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock()), ('file', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('label', wagtail.core.blocks.TextBlock(required=False))]))], icon='doc-empty'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tools',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock()), ('file', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('label', wagtail.core.blocks.TextBlock(required=False))]))], icon='doc-empty'))], blank=True, null=True),
        ),
    ]
