# Generated by Django 2.0.6 on 2018-06-18 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_auto_20180617_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='resources_normalized',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='tools_normalized',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='resources',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='doc-empty'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tools',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='doc-empty'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('kurs', 'Kurs'), ('coaching', 'Coaching')], max_length=100),
        ),
    ]
