# Generated by Django 2.0.6 on 2018-06-19 19:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20180618_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='resources_normalized',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='helper field for graphql api', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tools_normalized',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='helper field for graphql api', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='video_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
