# Generated by Django 2.0.6 on 2018-06-21 06:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_auto_20180619_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='video_thumbnail_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
