query ActionPlanQuery($slug: String!) {
  moduleUserGoal(moduleSlug: $slug) {
    goal {
      id
      text
      level
      module {
        id
        slug
        title
      }
    }
  }
  user {
    id
    usermoduleprogressSet(module_Slug: $slug) {
      edges {
        node {
          id
          learningsText
          impactText
          measurementText
          measuresText
          timeFrameText
          resourcesSkillsText
          commitmentSupportText
        }
      }
    }
  }
}
