# Generated by Django 2.0.6 on 2018-09-19 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('focus', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenceentry',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Competence'),
        ),
        migrations.AddField(
            model_name='competenceentry',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.Focus'),
        ),
    ]
