# Generated by Django 2.0.6 on 2018-07-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenceentry',
            options={'verbose_name': 'Kompetenzeintrag', 'verbose_name_plural': 'Kompetenzeinträge'},
        ),
    ]
