# Generated by Django 2.0.6 on 2018-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20180718_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
