mutation DefineUserGoal($moduleSlug: String!, $goalLevel: String!) {
  defineUserGoal(moduleSlug: $moduleSlug, goalLevel: $goalLevel) {
    ok
    message
    userGoal {
      goal {
        id
        text
        level
      }
    }
  }
}
