query ModuleGoalsQuery($slug: String!) {
  modules(slug: $slug) {
    edges {
      node {
        slug
        goalSet {
          edges {
            node {
              text
              level
            }
          }
        }
      }
    }
  }
}
