query ModuleGoalsQuery($slug:String!) {
  allUserGoals(goal_Module_Slug: $slug) {
    edges {
      node {
        user {
          username
        }
        goal {
          text
          level
          module {
            slug
          }
        }
      }
    }
  }
  modules(slug: $slug) {
    edges {
      node {
        slug
        goalSet {
          edges {
            node {
              id
              text
              level
            }
          }
        }
      }
    }
  }
}
