query FocusCompetencesQuery {
  categories {
    edges {
      node {
        slug
        title
        competenceSet {
          edges {
            node {
              title
              description
              slug
            }
          }
        }
      }
    }
  }
}
