query FocusCompetencesQuery {
  categories {
    edges {
      node {
        id
        slug
        competenceSet {
          edges {
            node {
              id
              slug
              title
            }
          }
        }
      }
    }
  }
}
