query FocusQuery {
  userFocus(active: true) {
    edges {
      node {
        created
        competenceentrySet {
          edges {
            node {
              id
              competence {
                id
                slug
                title
                category {
                  id
                  slug
                  title
                }
              }
              currentLevel
              nextEvaluation
            }
          }
        }
      }
    }
  }
}
