# Generated by Django 2.0.6 on 2018-08-06 13:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Module')),
            ],
            options={
                'verbose_name': 'UserModuleProgress',
                'verbose_name_plural': 'UserModules',
            },
        ),
        migrations.CreateModel(
            name='UserUnitProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('module_progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.UserModuleProgress')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Unit')),
            ],
            options={
                'verbose_name': 'UserUnitProgress',
                'verbose_name_plural': 'UserUnits',
            },
        ),
    ]
