# Generated by Django 2.0.6 on 2018-06-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max', models.PositiveIntegerField(default=10, verbose_name='Max Value')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Current Value')),
            ],
            options={
                'verbose_name': 'Action Plan',
                'verbose_name_plural': 'F Action Pläne',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max', models.PositiveIntegerField(default=10, verbose_name='Max Value')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Current Value')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'E Evaluationen',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Ziel',
                'verbose_name_plural': 'D Ziele',
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Module')),
            ],
            options={
                'verbose_name': 'Lernmodul-Fortschritt',
                'verbose_name_plural': 'B Lernmodul-Fortschritte',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('proposed_modules', models.ManyToManyField(blank=True, to='modules.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fortschritt',
                'verbose_name_plural': 'A Fortschritte',
            },
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.Unit')),
                ('user_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.UserModule')),
            ],
            options={
                'verbose_name': 'Lernangebot-Fortschritt',
                'verbose_name_plural': 'C Lernangebote-Fortschritte',
            },
        ),
        migrations.AddField(
            model_name='usermodule',
            name='user_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.UserProgress'),
        ),
        migrations.AddField(
            model_name='target',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.UserModule'),
        ),
        migrations.AddField(
            model_name='target',
            name='user_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.UserProgress'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Target'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progress.Target'),
        ),
    ]
