# Generated by Django 2.0.6 on 2018-07-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20180626_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplan',
            name='target',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='target',
        ),
        migrations.RemoveField(
            model_name='target',
            name='module',
        ),
        migrations.RemoveField(
            model_name='target',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActionPlan',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
