# Generated by Django 2.0.6 on 2018-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_usergoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergoal',
            options={'verbose_name': 'UserGoal', 'verbose_name_plural': 'UserGoals'},
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='custom_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
