# Generated by Django 2.0.6 on 2018-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20180723_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userunitprogress',
            old_name='user_module',
            new_name='module_progress',
        ),
    ]
