# Generated by Django 2.0.6 on 2018-09-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20180903_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='learnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
