# Generated by Django 2.0.6 on 2018-06-25 07:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0020_add-verbose-name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('skill', models.CharField(help_text="e.g. 'Leadership'", max_length=255)),
                ('teaser', models.TextField()),
                ('description', wagtail.core.fields.RichTextField()),
                ('video_id', models.PositiveIntegerField(blank=True, help_text='Vimeo video id (https://vimeo.com/<this-id>)', null=True)),
                ('video_description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('video_thumbnail_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('resources', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='doc-empty'))], blank=True, null=True)),
                ('resources_normalized', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='helper field for graphql api', null=True)),
                ('tools', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='link')), ('document', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('description', wagtail.core.blocks.CharBlock())], icon='doc-empty'))], blank=True, null=True)),
                ('tools_normalized', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='helper field for graphql api', null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Lernmodul',
                'verbose_name_plural': 'Lernmodule',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('teaser', models.TextField()),
                ('type', models.CharField(choices=[('webinar', 'Webinar'), ('kurs', 'Kurs'), ('coaching', 'Coaching')], max_length=100)),
                ('count', models.CharField(help_text="e.g. '3 Veranstaltungen'", max_length=255)),
                ('duration', models.CharField(help_text="e.g. 'je 2 Tage'", max_length=255)),
            ],
            options={
                'verbose_name': 'Lernangebot',
                'verbose_name_plural': 'Lernangebote',
            },
            bases=('wagtailcore.page',),
        ),
    ]
