# Generated by Django 2.0.6 on 2018-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='unit',
            name='price',
            field=models.CharField(default='', help_text="e.g. 'CHF 150'", max_length=255),
        ),
    ]
