# Generated by Django 2.0.6 on 2018-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_component',
            field=models.CharField(default='EmptyIcon', max_length=100),
        ),
    ]
