# Generated by Django 2.0.6 on 2018-08-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('level', models.PositiveIntegerField(blank=True, default=0, help_text='Ziel-Level', null=True)),
                ('goal_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Ziel',
                'verbose_name_plural': 'Ziele',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('kurs', 'Kurs'), ('coaching', 'Coaching'), ('lernfilm', 'Lernfilm'), ('webex', 'Webex')], max_length=100),
        ),
    ]
