# Generated by Django 2.0.6 on 2018-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_category_icon_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('kurs', 'Kurs'), ('hybrid', 'Hybrid'), ('coaching', 'Coaching'), ('tinder', 'Tinder'), ('lernfilm', 'Lernfilm'), ('webex', 'Webex')], max_length=100),
        ),
    ]
