# Generated by Django 2.0.6 on 2018-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20180807_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('kurs', 'Kurs'), ('coaching', 'Coaching'), ('tinder', 'Tinder'), ('lernfilm', 'Lernfilm'), ('webex', 'Webex')], max_length=100),
        ),
    ]
