# Generated by Django 2.0.6 on 2018-08-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='teaser',
        ),
    ]
