query ModulesProgressQuery {
  allModulesProgress {
    edges {
      node {
        id
        module {
          id
          teaser
        }
        moduleUnits(first:2) {
          edges {
            node {
              id
            }
          }
        }
        user {
          id
          username
          firstName
          lastName
          email
        }
      }
    }
  }
}
