query CategoriesQuery {
  categories {
    edges {
      node {
        title
        slug
        containers {
          edges {
            node {
              title
              slug
            }
          }
        }
      }
    }
  }
}
