query CategoriesQuery {
  categories {
    edges {
      node {
        title
        slug
        icon
      }
    }
  }

  userModules {
    edges {
      node {
        status
        module {
          id
          title
          slug
          heroImage
          skill
          teaser
        }
      }
    }
  }
}
