query ContainersQuery {
  containers {
    edges {
      node {
        title
        slug
        units {
          edges {
            node {
              title
              teaser
              type
            }
          }
        }
      }
    }
  }
}
