query ContainerQuery {
  containers(slug: "accusamus-quam-eos-enim") {
    edges {
      node {
        title
        slug
        units {
          edges {
            node {
              title
              teaser
              type
            }
          }
        }
      }
    }
  }
}
