query ModulesProgressFilteredQuery {
  allModulesProgress(user_Username:"test") {
    edges {
      node {
        id
        pk
        module {
          id
          teaser
        }
        moduleUnits(first:2) {
          edges {
            node {
              id
            }
          }
        }
        user {
          id
          username
          firstName
          lastName
          email
        }
      }
    }
  }
}
