query ModuleQuery($slug: String!) {
  modules(slug: $slug) {
    edges {
      node {
        title
        slug
        tools
        resources
        description
        heroImage
        skill
        videoId
        videoDescription
        videoThumbnailData
        category
        units {
          edges {
            node {
              title
              teaser
              type
              count
              duration
            }
          }
        }
      }
    }
  }
}
