query ModuleQuery($slug: String!, $username: String!) {
  modules(slug: $slug) {
    edges {
      node {
        title
        slug
        tools
        resources
        description
        heroImage
        skill
        videoId
        videoDescription
        videoThumbnailData
        category
        goalSet {
          edges {
            node {
              text
              level
            }
          }
        }
        units {
          edges {
            node {
              slug
              title
              teaser
              type
              count
              duration
            }
          }
        }
      }
    }
  }

  allModulesProgress(user_Username: $username, module_Slug: $slug) {
    edges {
      node {
        id
      }
    }
  }

  userModuleUnits(username: $username, moduleSlug: $slug) {
    edges {
      node {
        status
        unit {
          id
          slug
          title
          teaser
          type
          count
          duration
        }
      }
    }
  }
}
