query ModulesQuery {
  modules(slug:"effizient-kommunizieren") {
    edges {
      node {
        id,
        slug,
        title,
        category,
        teaser,
        description
      }
    }
  }
}
