query ModuleQuery($slug: String!) {
  modules(slug: $slug) {
    edges {
      node {
        title
        slug
        tools
        resources
        description
        heroImage
        skill
        videoId
        videoDescription
        videoThumbnailData
        category
        goalSet {
          edges {
            node {
              id
              text
              level
            }
          }
        }
        units {
          edges {
            node {
              slug
              title
              teaser
              type
              count
              duration
            }
          }
        }
      }
    }
  }

  allModulesProgress(module_Slug: $slug) {
    edges {
      node {
        id
      }
    }
  }

  userModuleUnits(moduleSlug: $slug) {
    edges {
      node {
        status
        unit {
          id
          slug
          title
          teaser
          type
          count
          duration
        }
      }
    }
  }
}
