query UnitQuery($slug: String!) {
  unit(slug: $slug) {
    slug
    title
    moduleSlug
    moduleTitle
    categorySlug
    categoryTitle
    teaser
    lead
    description
    objectives
    content
    teacher
    requirements
    type
    count
    duration
    price
  }
}
