query UnitQuery($slug: String!) {
  unit: unit(slug: $slug) {
    slug
    title
    moduleSlug
    moduleTitle
    categorySlug
    categoryTitle
    teaser
    description
    type
    count
    duration
    price
  }
}
