query UserModuleUnits($username: String!, $moduleSlug: String!) {
  userModuleUnits(username: $username, moduleSlug: $moduleSlug) {
    edges {
      node {
        status
        unit {
          id
          title
          teaser
          type
          count
          duration
        }
      }
    }
  }
}
