query UserModuleQuery {
  userModule(id:"VXNlck1vZHVsZU5vZGU6MQ==") {
    id,
    pk,
    module {
      id,
      teaser
    },
    userUnits {
      edges {
        node {
          id
        }
      }
    },
    user {
      id,
      username,
      firstName,
      lastName,
      email
    }
  }
}
