mutation deleteModuleProgressMutation($username: String!, $moduleSlug: String!) {
  deleteModuleProgress(username: $username, moduleSlug: $moduleSlug) {
    deleted
    moduleSlug
    failed
    exception
  }
}
