mutation startUnitProgressMutation($unitSlug: String!, $moduleSlug: String!) {
  startUnitProgress(unitSlug: $unitSlug, moduleSlug: $moduleSlug) {
    created
    unitSlug
    failed
    exception
  }
}
